artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/midhu262/Datasets/raw/main/archive.zip
  local_data_file: artifacts/data_ingestion/concrete_data.zip
  unzip_dir: artifacts/data_ingestion
