artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/midhu262/Datasets/raw/main/archive.zip
  local_data_file: artifacts/data_ingestion/concrete_data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/concrete_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt